import os
BOT_TOKEN = os.getenv("BOT_TOKEN", "")

ADMIN_IDS = [1432396874]

CHANNELS = [
    {
        "id": "@YIA_Shofirkon_tumani",
        "name": "Shofirkon Yoshlari",
        "invite_link": "https://t.me/YIA_Shofirkon_tumani"
    },
    {
        "id": "@YIABuxoro_viloyat_boshqarmasi",
        "name": "Buxoro Yoshlari",
        "invite_link": "https://t.me/YIABuxoro_viloyat_boshqarmasi"
    },
]

CANDIDATES = [
    {"id": 1,  "name": "Ostonova Shahzoda Toshevna",          "mahalla": "1-umumiy o'rta ta'lim maktabi"},
    {"id": 2,  "name": "Sharipova Roxat Zokirovna",           "mahalla": "2-umumiy o'rta ta'lim maktabi"},
    {"id": 3,  "name": "Yo'ldasheva Nigora Xasanovna",        "mahalla": "3-umumiy o'rta ta'lim maktabi"},
    {"id": 4,  "name": "Narzullayev Dilshod Sayfullayevich",  "mahalla": "4-umumiy o'rta ta'lim maktabi"},
    {"id": 5,  "name": "Jamolov Otabek Ramazonovich",         "mahalla": "5-umumiy o'rta ta'lim maktabi"},
    {"id": 6,  "name": "Tilloyev Bahodir Ravshanovich",       "mahalla": "6-umumiy o'rta ta'lim maktabi"},
    {"id": 7,  "name": "Akramov Qahramon Qurbonovich",        "mahalla": "7-umumiy o'rta ta'lim maktabi"},
    {"id": 8,  "name": "Asadov To'lagan Cho'liboyevich",      "mahalla": "8-umumiy o'rta ta'lim maktabi"},
    {"id": 9,  "name": "Rajabov Fayzillo Shokirovich",        "mahalla": "9-umumiy o'rta ta'lim maktabi"},
    {"id": 10, "name": "O'rinov Ubaydullo Erkinovich",        "mahalla": "10-umumiy o'rta ta'lim maktabi"},
    {"id": 11, "name": "Tursunov Jo'rbek To'ramurodovich",    "mahalla": "11-umumiy o'rta ta'lim maktabi"},
    {"id": 12, "name": "Qo'shshayev Sanjar Iskandarovich",    "mahalla": "12-umumiy o'rta ta'lim maktabi"},
    {"id": 13, "name": "Rahmatov Feruz Axror o'g'li",         "mahalla": "13-umumiy o'rta ta'lim maktabi"},
    {"id": 14, "name": "Toshev Mirali Shokirovich",           "mahalla": "14-umumiy o'rta ta'lim maktabi"},
    {"id": 15, "name": "Tilloyev Obid Roziqovich",            "mahalla": "15-umumiy o'rta ta'lim maktabi"},
    {"id": 16, "name": "Yusupova Surayyo Bobojonovna",        "mahalla": "16-umumiy o'rta ta'lim maktabi"},
    {"id": 17, "name": "Temirov Hayitjon Narzullayevich",     "mahalla": "17-umumiy o'rta ta'lim maktabi"},
    {"id": 18, "name": "Sultonov Ravshan Nurilloyevich",      "mahalla": "18-umumiy o'rta ta'lim maktabi"},
    {"id": 19, "name": "Jumayeva Muxayyo Xo'jayevna",         "mahalla": "19-umumiy o'rta ta'lim maktabi"},
    {"id": 20, "name": "Hojiyev Umid Mirqul o'g'li",          "mahalla": "20-umumiy o'rta ta'lim maktabi"},
    {"id": 21, "name": "Vohidov Abduvaxob Iskandarovich",     "mahalla": "21-umumiy o'rta ta'lim maktabi"},
    {"id": 22, "name": "Muzaffarov Ozod Maxsud o'g'li",       "mahalla": "22-umumiy o'rta ta'lim maktabi"},
    {"id": 23, "name": "Abdiyev Sa'dullo Abdulloyevich",      "mahalla": "23-umumiy o'rta ta'lim maktabi"},
    {"id": 24, "name": "Kamolov Olimjon Rahmatovich",         "mahalla": "24-umumiy o'rta ta'lim maktabi"},
    {"id": 25, "name": "Yusupova Umida Roziqovna",            "mahalla": "25-umumiy o'rta ta'lim maktabi"},
    {"id": 26, "name": "Qudratov Ne'mat Sunnatovich",         "mahalla": "26-umumiy o'rta ta'lim maktabi"},
    {"id": 27, "name": "Abdullayev Nutfullo Nasullayevich",   "mahalla": "27-umumiy o'rta ta'lim maktabi"},
    {"id": 28, "name": "Rahmonov Zafar Jabborovich",          "mahalla": "28-umumiy o'rta ta'lim maktabi"},
    {"id": 29, "name": "Jumayev Oybek Savriddinovich",        "mahalla": "29-umumiy o'rta ta'lim maktabi"},
    {"id": 30, "name": "Sharipov Botir Sulton o'g'li",        "mahalla": "30-umumiy o'rta ta'lim maktabi"},
    {"id": 31, "name": "Norqulova Ozoda Mansurovna",          "mahalla": "31-umumiy o'rta ta'lim maktabi"},
    {"id": 32, "name": "Shodiev Istam Yunusovich",            "mahalla": "32-umumiy o'rta ta'lim maktabi"},
    {"id": 33, "name": "Sharipova Dilfuza Mavlonovna",        "mahalla": "33-umumiy o'rta ta'lim maktabi"},
    {"id": 34, "name": "Xo'jayev Vaxob Obidovich",            "mahalla": "34-umumiy o'rta ta'lim maktabi"},
    {"id": 35, "name": "Narzullayev Farxod Sayfulloyevich",   "mahalla": "35-umumiy o'rta ta'lim maktabi"},
    {"id": 36, "name": "Ergasheva Lobar Qutfullayeva",        "mahalla": "36-umumiy o'rta ta'lim maktabi"},
    {"id": 37, "name": "Ibroximov Baxriddin Erkin o'g'li",    "mahalla": "37-umumiy o'rta ta'lim maktabi"},
    {"id": 38, "name": "Baqoyev Shohimardon Davronovich",     "mahalla": "38-davlat umumta'lim maktabi"},
    {"id": 39, "name": "Sulaymonov Maman Muslimovich",        "mahalla": "39-umumiy o'rta ta'lim maktabi"},
    {"id": 40, "name": "Asadova Nodira Muhammadovna",         "mahalla": "40-umumiy o'rta ta'lim maktabi"},
    {"id": 41, "name": "Vafiyeva Dilbar Xalimjonovna",        "mahalla": "41-umumiy o'rta ta'lim maktabi"},
    {"id": 42, "name": "Barotova Charos Rasulovna",           "mahalla": "42-umumiy o'rta ta'lim maktabi"},
    {"id": 43, "name": "Bozorov Davlat Ergashovich",          "mahalla": "43-umumiy o'rta ta'lim maktabi"},
    {"id": 44, "name": "Xudoynazarov Umidjon Sharipovich",    "mahalla": "44-umumiy o'rta ta'lim maktabi"},
    {"id": 45, "name": "Toshev Ikrom Davronovich",            "mahalla": "45-umumiy o'rta ta'lim maktabi"},
    {"id": 46, "name": "Xasanov Zavqiddin Nuriddinovich",     "mahalla": "46-umumiy o'rta ta'lim maktabi"},
    {"id": 47, "name": "Adizov Rashid Tursunovich",           "mahalla": "47-umumiy o'rta ta'lim maktabi"},
    {"id": 48, "name": "Shirinova Munira Shukurullayeva",     "mahalla": "48-umumiy o'rta ta'lim maktabi"},
    {"id": 49, "name": "Sharipov Umid Narzullayevich",        "mahalla": "49-umumiy o'rta ta'lim maktabi"},
    {"id": 50, "name": "Rustamov G'ayrat Safarovich",         "mahalla": "50-umumiy o'rta ta'lim maktabi"},
    {"id": 51, "name": "Usmonov G'ayrat Umedboyevich",        "mahalla": "51-umumiy o'rta ta'lim maktabi"},
    {"id": 52, "name": "Xo'jamov Asqar Davlatovich",          "mahalla": "52-umumiy o'rta ta'lim maktabi"},
    {"id": 53, "name": "Nurov Baxromjon Qaxramonovich",       "mahalla": "53-umumiy o'rta ta'lim maktabi"},
    {"id": 54, "name": "Shodmonov Toshpo'lat Shodiyevich",    "mahalla": "54-umumiy o'rta ta'lim maktabi"},
    {"id": 55, "name": "Muxtorov Anvar Salimovich",           "mahalla": "55-umumiy o'rta ta'lim maktabi"},
    {"id": 56, "name": "Xo'jayeva Mavluda Qushshayeva",       "mahalla": "56-umumiy o'rta ta'lim maktabi"},
    {"id": 57, "name": "Boltayev Feruz",                      "mahalla": "Ixtisoslashtirilgan maktab"},
    {"id": 58, "name": "Barnoev Jasur Baxtiyorovich",         "mahalla": "Ma'rifat chashmasi NTM"},
    {"id": 59, "name": "Ro'ziyev Laziz Fazliddinovich",       "mahalla": "Idrok EDU NTM"},
]
